# Generated by Django 4.2.1 on 2023-05-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Book Name', max_length=255)),
                ('description', models.CharField(help_text='Enter Book Name', max_length=255)),
            ],
        ),
    ]
