# Generated by Django 4.2.1 on 2023-05-08 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_repositor', '0003_bookauthor_author_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookauthor',
            old_name='extra_sauce',
            new_name='extra_live',
        ),
    ]
