# Generated by Django 4.2.1 on 2023-05-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_repositor', '0004_rename_extra_sauce_bookauthor_extra_live'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookauthor',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bookauthor',
            name='book',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='BookAuthor',
        ),
    ]
