# Generated by Django 4.2.1 on 2023-05-08 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('book_repositor', '0006_author_bookauthor_author_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Book Page',
                'verbose_name_plural': 'Book Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
