# Generated by Django 4.2.1 on 2023-05-08 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_repositor', '0007_bookpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookPage',
        ),
    ]
